# Association Rules Examples
* Package: MLxtend
* Algorithms: Apriori

# Business Problem Understanding

In [1]:
# -- Import libraries --
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

# Load the Dataset

* The dataset includes transactions between 12-01-2010 and 12-09-2011

* **Data Dictionary**: 
    * InvoiceNo: An invoice number is a unique number generated by a business issuing an invoice to a client. This number is included on the invoice and it is used for payment tracking purposes. **Note that, when the number starts with C, this means cancellation**. The type of features is string, categorical.
    * StockCode: Product (item) code. It is unique to each product. This feature is string, categorical.
    * Description: Product name. This feature is string, categorical.
    * Quantity: The quantity of this product per transaction. This feature is numerical discrete.
    * InvoiceDate: When the transaction is done. This feature is a date.
    * UnitPrice: Price per unit. This feature is numerical continuous.
    * CustomerID: unique per each customer. It is numerical.
    * Country: The country where the customer lives. This feature is string, categorical.

In [2]:
# -- Import data --
df = pd.read_excel('http://archive.ics.uci.edu/ml/machine-learning-databases/00352/Online%20Retail.xlsx')

KeyboardInterrupt:

In [ ]:
# -- properties of the dataset --
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

In [ ]:
# -- preview --
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [ ]:
df['Country'].value_counts()

Country
United Kingdom          495478
Germany                   9495
France                    8557
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
USA                        291
Hong Kong                  288
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     19
Saudi Arabia                10
Name: count, dtype: int64

# Examine the Dataset

In [ ]:
# -- Clean up spaces in description and remove any rows that don't have a valid invoice --
df['Description'] = df['Description'].str.strip()

df.dropna(axis=0,
          subset=['InvoiceNo'],
          inplace=True)

In [ ]:
# -- numbers of rows and columns --
df.shape

(541909, 8)

In [ ]:
# -- Remove cancelled transactions --
df['InvoiceNo'] = df['InvoiceNo'].astype('str')
df[df['InvoiceNo'].str.contains('C')]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
...,...,...,...,...,...,...,...,...
540449,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,2011-12-09 09:57:00,0.83,14397.0,United Kingdom
541541,C581499,M,Manual,-1,2011-12-09 10:28:00,224.69,15498.0,United Kingdom
541715,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,2011-12-09 11:57:00,10.95,15311.0,United Kingdom
541716,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,2011-12-09 11:58:00,1.25,17315.0,United Kingdom
541717,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,2011-12-09 11:58:00,1.25,17315.0,United Kingdom

# France Market

## Convert dataset to one-hot key (binary representation)

In [ ]:
# -- We are interested in what products French usually purchase togehter or what we can recommend to them? --

basket = (df[df['Country'] =="France"]
          .pivot_table(index="InvoiceNo", 
                       columns="Description", 
                       values="Quantity", 
                       aggfunc="count",
                       fill_value=0) )

In [ ]:
# -- Product list --
basket.columns

Index(['10 COLOUR SPACEBOY PEN', '12 COLOURED PARTY BALLOONS',
       '12 EGG HOUSE PAINTED WOOD', '12 MESSAGE CARDS WITH ENVELOPES',
       '12 PENCIL SMALL TUBE WOODLAND', '12 PENCILS SMALL TUBE RED RETROSPOT',
       '12 PENCILS SMALL TUBE SKULL', '12 PENCILS TALL TUBE POSY',
       '12 PENCILS TALL TUBE RED RETROSPOT', '12 PENCILS TALL TUBE WOODLAND',
       ...
       'WRAP VINTAGE PETALS  DESIGN', 'YELLOW COAT RACK PARIS FASHION',
       'YELLOW GIANT GARDEN THERMOMETER', 'YELLOW SHARK HELICOPTER',
       'ZINC  STAR T-LIGHT HOLDER', 'ZINC FOLKART SLEIGH BELLS',
       'ZINC HERB GARDEN CONTAINER', 'ZINC METAL HEART DECORATION',
       'ZINC T-LIGHT HOLDER STAR LARGE', 'ZINC T-LIGHT HOLDER STARS SMALL'],
      dtype='object', name='Description', length=1564)

In [ ]:
# -- Preview --
basket.head()

Description,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE SKULL,12 PENCILS TALL TUBE POSY,12 PENCILS TALL TUBE RED RETROSPOT,12 PENCILS TALL TUBE WOODLAND,...,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,YELLOW SHARK HELICOPTER,ZINC STAR T-LIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536370,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536852,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536974,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537065,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537463,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# -- Size of the basket --
basket.shape

(461, 1564)

In [ ]:
basket[basket.iloc[:,1]>0]

Description,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE SKULL,12 PENCILS TALL TUBE POSY,12 PENCILS TALL TUBE RED RETROSPOT,12 PENCILS TALL TUBE WOODLAND,...,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,YELLOW SHARK HELICOPTER,ZINC STAR T-LIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
544115,1,1,0,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
546678,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
547504,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
553411,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
561795,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
579792,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# Show a subset of columns
basket.iloc[:,[0,1,2,3,4,5,6,7]].head()

Description,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE SKULL,12 PENCILS TALL TUBE POSY
InvoiceNo,,,,,,,,
536370,0,0,0,0,0,0,0,0
536852,0,0,0,0,0,0,0,0
536974,0,0,0,0,0,0,0,0
537065,0,0,0,0,0,0,0,0
537463,0,0,0,0,0,0,0,0

In [ ]:
basket['POSTAGE']

InvoiceNo
536370     1
536852     1
536974     1
537065     1
537463     1
          ..
C579532    1
C579562    0
C580161    1
C580263    0
C581316    0
Name: POSTAGE, Length: 461, dtype: int64

In [ ]:
# -- Drop Postage column -- 
basket.drop('POSTAGE', inplace=True, axis=1)

In [ ]:
basket.head(10)

Description,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE SKULL,12 PENCILS TALL TUBE POSY,12 PENCILS TALL TUBE RED RETROSPOT,12 PENCILS TALL TUBE WOODLAND,...,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,YELLOW SHARK HELICOPTER,ZINC STAR T-LIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536370,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536852,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536974,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537065,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537463,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537468,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537693,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537897,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537967,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
538008,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# -- Convert Unit --
def convert(x):
    if x == 0:
        return 0
    elif x >= 1:
        return 1

In [ ]:
basket = basket.applymap(convert)
basket

Description,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE SKULL,12 PENCILS TALL TUBE POSY,12 PENCILS TALL TUBE RED RETROSPOT,12 PENCILS TALL TUBE WOODLAND,...,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,YELLOW SHARK HELICOPTER,ZINC STAR T-LIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536370,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536852,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536974,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537065,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537463,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C579532,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C579562,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C580161,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C580263,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
C581316,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## Frequent Items

In [ ]:
# Build up the frequent items
frequent_itemsets = apriori(basket, 
                            min_support=0.07, 
                            use_colnames=True)

In [ ]:
frequent_itemsets

     support                                           itemsets
0   0.084599                       (ALARM CLOCK BAKELIKE GREEN)
1   0.086768                        (ALARM CLOCK BAKELIKE PINK)
2   0.080260                         (ALARM CLOCK BAKELIKE RED)
3   0.086768                             (DOLLY GIRL LUNCH BOX)
4   0.082430                          (JUMBO BAG RED RETROSPOT)
5   0.108460                           (LUNCH BAG APPLE DESIGN)
6   0.073753                      (LUNCH BAG DOLLY GIRL DESIGN)
7   0.132321                          (LUNCH BAG RED RETROSPOT)
8   0.104121                        (LUNCH BAG SPACEBOY DESIGN)
9   0.101952                               (LUNCH BAG WOODLAND)
10  0.123644                 (LUNCH BOX WITH CUTLERY RETROSPOT)
11  0.088937                           (MINI PAINT SET VINTAGE)
12  0.086768                  (PACK OF 72 RETROSPOT CAKE CASES)
13  0.147505                    (PLASTERS IN TIN CIRCUS PARADE)
14  0.119306                         (PLASTERS IN TIN SPACEBOY)
15  0.145336                 (PLASTERS IN TIN WOODLAND ANIMALS)
16  0.162690                               (RABBIT NIGHT LIGHT)
17  0.082430                      (RED RETROSPOT CHARLOTTE BAG)
18  0.119306                         (RED RETROSPOT MINI CASES)
19  0.156182                    (RED TOADSTOOL LED NIGHT LIGHT)
20  0.117137                         (REGENCY CAKESTAND 3 TIER)
21  0.073753                  (RETROSPOT TEA SET CERAMIC 11 PC)
22  0.093275                (ROUND SNACK BOXES SET OF 4 FRUITS)
23  0.138829               (ROUND SNACK BOXES SET OF4 WOODLAND)
24  0.112798               (SET/20 RED RETROSPOT PAPER NAPKINS)
25  0.117137                      (SET/6 RED SPOTTY PAPER CUPS)
26  0.108460                    (SET/6 RED SPOTTY PAPER PLATES)
27  0.106291                               (SPACEBOY LUNCH BOX)
28  0.104121                (STRAWBERRY LUNCH BOX WITH CUTLERY)
29  0.080260                          (TEA PARTY BIRTHDAY CARD)
30  0.078091  (PLASTERS IN TIN CIRCUS PARADE, PLASTERS IN TI...
31  0.086768  (PLASTERS IN TIN WOODLAND ANIMALS, PLASTERS IN...
32  0.088937  (PLASTERS IN TIN WOODLAND ANIMALS, PLASTERS IN...
33  0.086768  (SET/6 RED SPOTTY PAPER CUPS, SET/20 RED RETRO...
34  0.086768  (SET/20 RED RETROSPOT PAPER NAPKINS, SET/6 RED...
35  0.104121  (SET/6 RED SPOTTY PAPER CUPS, SET/6 RED SPOTTY...
36  0.084599  (SET/6 RED SPOTTY PAPER CUPS, SET/20 RED RETRO...

## Create Assciation Rules

In [ ]:
# -- Create the rules --
rules = association_rules(frequent_itemsets, 
                          metric="lift", 
                          min_threshold=1)
rules[['antecedents','consequents','support','confidence','lift']]

,antecedents,consequents,support,confidence,lift
0,(PLASTERS IN TIN CIRCUS PARADE),(PLASTERS IN TIN SPACEBOY),0.078091,0.529412,4.437433
1,(PLASTERS IN TIN SPACEBOY),(PLASTERS IN TIN CIRCUS PARADE),0.078091,0.654545,4.437433
2,(PLASTERS IN TIN WOODLAND ANIMALS),(PLASTERS IN TIN CIRCUS PARADE),0.086768,0.597015,4.047410
3,(PLASTERS IN TIN CIRCUS PARADE),(PLASTERS IN TIN WOODLAND ANIMALS),0.086768,0.588235,4.047410
4,(PLASTERS IN TIN WOODLAND ANIMALS),(PLASTERS IN TIN SPACEBOY),0.088937,0.611940,5.129172
5,(PLASTERS IN TIN SPACEBOY),(PLASTERS IN TIN WOODLAND ANIMALS),0.088937,0.745455,5.129172
6,(SET/6 RED SPOTTY PAPER CUPS),(SET/20 RED RETROSPOT PAPER NAPKINS),0.086768,0.740741,6.566952
7,(SET/20 RED RETROSPOT PAPER NAPKINS),(SET/6 RED SPOTTY PAPER CUPS),0.086768,0.769231,6.566952
8,(SET/20 RED RETROSPOT PAPER NAPKINS),(SET/6 RED SPOTTY PAPER PLATES),0.086768,0.769231,7.092308
9,(SET/6 RED SPOTTY PAPER PLATES),(SET/20 RED RETROSPOT PAPER NAPKINS),0.086768,0.800000,7.092308
10,(SET/6 RED SPOTTY PAPER CUPS),(SET/6 RED SPOTTY PAPER PLATES),0.104121,0.888889,8.195556
11,(SET/6 RED SPOTTY PAPER PLATES),(SET/6 RED SPOTTY PAPER CUPS),0.104121,0.960000,8.195556
12,"(SET/6 RED SPOTTY PAPER CUPS, SET/20 RED RETRO...",(SET/6 RED SPOTTY PAPER PLATES),0.084599,0.975000,8.989500
13,"(SET/6 RED SPOTTY PAPER CUPS, SET/6 RED SPOTTY...",(SET/20 RED RETROSPOT PAPER NAPKINS),0.084599,0.812500,7.203125
14,"(SET/20 RED RETROSPOT PAPER NAPKINS, SET/6 RED...",(SET/6 RED SPOTTY PAPER CUPS),0.084599,0.975000,8.323611
15,(SET/6 RED SPOTTY PAPER CUPS),"(SET/20 RED RETROSPOT PAPER NAPKINS, SET/6 RED...",0.084599,0.722222,8.323611
16,(SET/20 RED RETROSPOT PAPER NAPKINS),"(SET/6 RED SPOTTY PAPER CUPS, SET/6 RED SPOTTY...",0.084599,0.750000,7.203125
17,(SET/6 RED SPOTTY PAPER PLATES),"(SET/6 RED SPOTTY PAPER CUPS, SET/20 RED RETRO...",0.084599,0.780000,8.989500

## Extract Specific Rules

In [ ]:
# -- Filter high lift and confidence vlaues --
rules[ (rules['lift'] >= 6) &
       (rules['confidence'] >= 0.8) ][['antecedents','consequents','support','confidence','lift']]

,antecedents,consequents,support,confidence,lift
10,(SET/6 RED SPOTTY PAPER CUPS),(SET/6 RED SPOTTY PAPER PLATES),0.104121,0.888889,8.195556
11,(SET/6 RED SPOTTY PAPER PLATES),(SET/6 RED SPOTTY PAPER CUPS),0.104121,0.960000,8.195556
12,"(SET/6 RED SPOTTY PAPER CUPS, SET/20 RED RETRO...",(SET/6 RED SPOTTY PAPER PLATES),0.084599,0.975000,8.989500
13,"(SET/6 RED SPOTTY PAPER CUPS, SET/6 RED SPOTTY...",(SET/20 RED RETROSPOT PAPER NAPKINS),0.084599,0.812500,7.203125
14,"(SET/20 RED RETROSPOT PAPER NAPKINS, SET/6 RED...",(SET/6 RED SPOTTY PAPER CUPS),0.084599,0.975000,8.323611

In [ ]:
basket['ALARM CLOCK BAKELIKE GREEN'].sum()

39

In [ ]:
basket['ALARM CLOCK BAKELIKE RED'].sum()

37